name: chucklepy

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: ["3.9", "3.11"]
    steps:
      - uses: actions/checkout@v4

      - name: Install Python, pipenv, and dependencies
        run: |
          pip install pipenv
          pipenv install --dev
          pipenv lock

      - name: Verify Virtual Environment
        run: |
          pipenv --venv

      - name: Install Project in Editable Mode
        run: |
          pipenv install -e .

      - name: Test with pytest
        run: |
          pipenv install pytest
          pipenv run python -m pytest