name: chucklepy

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: ["3.9", "3.11"]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Pipenv
        run: pip install pipenv

      - name: Install Dependencies
        run: |
          pipenv --python $(command -v python)
          pipenv install --dev
          pipenv lock 

      - name: Verify Virtual Environment
        run: pipenv --venv

      - name: Install Project in Editable Mode
        run: pipenv install -e .

      - name: Test with pytest
        run: |
          pipenv install pytest
          pipenv run python -m pytest